before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
before_install: gem install bundler -v 2.0.2
language: ruby
rvm:
- 2.6.3
services:
- postgresql
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  app: upvote-ideas
  on:
    repo: jobannon/upvote_api
  api_key:
    secure: FleddvnHbz0MVK+T6axcsmp5Ns6gfnWo1gUMsWkdHjUdE461xnX4XwMk4XVBnT6dfXgFqjd3OuHPeZ1E9DCKbmuczCvUeY2BxZgx/tAAZ/jwLkuMCXb8aKGBiEMPI90rDj/JuJDdcOfCRev86WsR+fqnT6FQlUU8gxjN8HNacDSxSy6gyEuMH6hoKEQxsto36gOGhaSzFnI7hB8Q/DoOf1wSLk+rsvIKY2tW75jPLAj0QblbwU0fJATyYkEl16U1IIoUp07qION+EUzMNSkY9ofQgMwbUk6DCMhejz8+nHWn6ZoE0U1l+tCwE1S+L/AAjKKJZaOdx2v/iWDxJ2Ri3ZweE5E5m+qWBM0BtkY8z+ZoCoKjKDf/LO9AG8azyR7nd+cf/JEQegkyqbQMGnQxOMsLIQBI+KrekL2NdcW+Emb9PV8RYH49dOx0iYhlJ/DNJsYr5vSAoA4mSkKk6fBIqpiVYVs1XKet4MMRPM83Uh9HmFyXs9JnDqAQzWIuiTvWz9oMrqsWQrADQk4FpZ1p3uetsiXCv1Qpl1lQZnqmmM64SSS7F+/9psy8uifJYGLFRXXkqyJaHPLLtKXbhNl8hvHhZeInX+ONO5IeMYePXQ9dUkjaNTQDzj+6dWiGPR/+wjUycubm/WGEkuv3XJosxRIUAWpmevtAcI+2ZPTkCJI=
env:
  global:
  - secure: nxSGSv6yp0RlwgNcfh/rAXl0aT22depD+l7zTqvtg8GE57XfXOU95IhUE1mxYIdO0msoRstrx1rIp4kjKHJCIOZ3BHkebv6AM5UNDc/xYOYO7X3rEQxNWqHSb7z2FOvewHpIG6/Abp38ZxuxcXNskEKbbCqbKdRq4OwWrzo0wjVLya+s3cS2JXVtfhcI8sokiKVLl66p5KFVgZ5Na032/U9/+tYMpeeJOn8tjuTNy6BtrH4UHNeGCs+KITDxCRJnsA/M+3P5v/brAFi1Tpuqj9KC9zH7i36axYIelsIuiHGcfczPXEqZebjcusObgg4H57uqwIget3rpIt5oZabXOB+KeVIbIe/9L+aJJDXLAQsSptD7iGfIM6K8plAFzt5Ubd2yZwlZ9CrtKp0y54560+99Cipy7zxpiIB0vKgh9FpmEn8Gj77CtIkwAzRU6ecH0Rb6O7XNRi3QUnPviNDo0+QHu5KTQuT5DQznzegQ9F5ZIUwewarR7J9sQJrU+0ykvV1jMHHi3vNmvSVDe/gFx7y/HGc8NWsrf4zpzjVPASvC2noO86a7NJUaS+3VhlXOc6ZiG5R5JWuwxSNLR2Eft+k3CB4GzkrvgI+UOr5ALmRZGquan5Dw25Q/B1/IjWoyTfVBERAL2uC+A/O9ZMN1Q/ZkNYUW98TGDBJ94Q6/c4I=
  - secure: eFLzWpkjnChqr5Dl1XcvojUaazKxD4U6CDB8NQtsP+5+0dOsYEoqBQxa8T/Uara9esEra97XmfFJZX8FmkEVCJXoeiNZbqXNhpt3nop6ndt12xrAt5fny66GUoGNK4IswGLixR4bluEId+N7iYo4Mfd32wVkzq0ju6FFxyCUdIitAVJ5/3HB+wT3fQu8tjmsysSm2Q9O6laBpcn+4QPKJOnQPdr0aDXgrCbbGofbkXeUpaAJA+RheF+h7IIABtRRG4MmTmDY/esWEShDKO+gQ/Ue2oYtBygeFg/hvk8vmSEPjjX2hSYs9mytOz3fjsxi7hWUjfpOQ7LjSPImLk8SwNSGSj3vVf1T3L3xm48haYtNhr2EREjF7QiYyN31FZk4zir6MheljH4KR1lgO7V9wyiCZQe0lJkfrxEAI7RpcRUeD4xKGA5qo5lwL9BmWBxji6L5d4K+Xx15RzR5+a4kMNJuA11VjdOigPemDkJ2ltl+wEVQ+7a70qUqZLxaXO4lbUmEABlyK/+8IpLQhAbwLptNIS9tWrXVwi7V6kjds7GC+M0WLcVtxX/ocN6CUJp3mS+BVuNrsy8j40TM5L5f0dJZLfwQrhMoQe7pspEoZQqUvRzX4gmTWZc0tpSkfWEVqQjFNAWfjNQ72MEtyoYNOQA7vvkrWJCJv1N7CbrohDQ=
